# Generated by Django 5.1.1 on 2024-09-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato')], max_length=15),
        ),
    ]
