# Generated by Django 5.1.1 on 2024-09-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('mascotas', '0002_alter_mascota_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='clientes.cliente'),
        ),
    ]
